/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import ClassesAuxiliares.Arrumador;
import ClassesAuxiliares.BancoDeDados;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;

/**
 *
 * @author SistemaIP
 */
public class AlterarConfiguracoes extends javax.swing.JFrame {

    
    ArrayList<JCheckBox> config = new ArrayList<>();
    ArrayList<Integer> valoresIn = new ArrayList<>();
    
    
    private final int Xminimo = 30;
    private final int Yminimo = 50;
    private final int alturaCH = 25;
    private final int larguraCH = 260;
    private final int espacoVerticalEntreCampos = 5;
    private final int limiteAlturaJanela = 480;
    
    /**
     * Creates new form AlterarConfiguracoes
     */
    public AlterarConfiguracoes() {
        initComponents();
        this.setTitle("Alterar Configurações Avançadas");
        this.setLocationRelativeTo(null);
        //this.setResizable(false);
        //this.setIconImage(Arrumador.comando().getIcone().getImage());
        this.setVisible(true);
        
        
        ResultSet r = BancoDeDados.comando().select("SELECT * FROM valores WHERE (valor1 = 0 OR valor1 = 1) AND rotulo <> 'centralizado';");
        int aux;
        
        try {
            while(r.next()){
                aux = r.getInt("valor1");
                config.add(new JCheckBox(r.getString("rotulo")));
                valoresIn.add(aux);
                config.get(config.size()-1).setSelected(aux>0);
            }
        } catch (SQLException ex) {
            Logger.getLogger(AlterarConfiguracoes.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for(int a=0;a<config.size();a++){
        
            config.get(a).setBounds(Xminimo,
                    Yminimo + (a * (alturaCH + espacoVerticalEntreCampos)),
                    larguraCH, alturaCH);
            this.add(config.get(a));
        
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTSalvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        BTSalvar.setText("Salvar e Sair");
        BTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTSalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .addComponent(BTSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BTSalvar)
                .addContainerGap(429, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTSalvarActionPerformed
      
        String SQL = "";
        
        for(int a=0;a<config.size();a++){
            
            if(valoresIn.get(a)>0 != config.get(a).isSelected()){
            //atualiza
            
                if(config.get(a).isSelected())
                    SQL = "UPDATE valores SET valor1 = 1 WHERE rotulo = '"+config.get(a).getText()+"';";
                else
                    SQL = "UPDATE valores SET valor1 = 0 WHERE rotulo = '"+config.get(a).getText()+"';";
                
                
                BancoDeDados.comando().update(SQL);
            }
        
        
        }
        this.dispose();
        
    }//GEN-LAST:event_BTSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarConfiguracoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarConfiguracoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTSalvar;
    // End of variables declaration//GEN-END:variables
}
