/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package janelas;

import ClassesAuxiliares.Arrumador;
import ClassesAuxiliares.BancoDeDados;
import ClassesAuxiliares.GeradorPDF;
//import ClassesAuxiliares.geradorCertificados;
import java.util.ArrayList;
import objetosBase.apresentacao;
import objetosBase.triviais.area;
import objetosBase.triviais.evento;
import objetosBase.triviais.modalidade;
import objetosBase.triviais.unidade;

/**
 *
 * @author SistemaIP
 */
public class GerarAnaisDoSeminario extends javax.swing.JFrame {

    private final ArrayList<evento> eventos;
    private ArrayList<apresentacao> apresentacoes;
    private final ArrayList<modalidade> modalidades;
    private final ArrayList<unidade> unidades;
    private final ArrayList<area> areas;
    ArrayList<String> orders;

    /**
     * Creates new form GerarAnaisDoSeminario
     */
    public GerarAnaisDoSeminario() {
        initComponents();

        this.setTitle("Gerar anais do seminário");
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        //this.setIconImage(Arrumador.comando().getIcone().getImage());

        CBEvento.removeAllItems();
        eventos = BancoDeDados.comando().getTodosEventos();
        for (evento evento : eventos) {
            CBEvento.addItem(evento.getNome());
        }
        CBModalidade.removeAllItems();
        CBModalidade.addItem("Todas");
        modalidades = BancoDeDados.comando().getModalidades();
        for (modalidade modalidade : modalidades) {
            CBModalidade.addItem(modalidade.getNome());
        }
        CBUnidade.removeAllItems();
        CBUnidade.addItem("Todas");
        unidades = BancoDeDados.comando().getUnidades();
        for (int a = 0; a < unidades.size(); a++) {
            CBUnidade.addItem(unidades.get(a).getNome());
        }

        orders = new ArrayList<>();
        CBOrder.removeAllItems();

        CBOrder.addItem("nome");
        orders.add("apresentacao.nome");
        CBOrder.addItem("id");
        orders.add("apresentacao.id");
        CBOrder.addItem("unidade, nome");
        orders.add("unidade, apresentacao.nome");
        CBOrder.addItem("unidade, id");
        orders.add("unidade, apresentacao.id");
        CBOrder.addItem("area, id");
        orders.add("area, apresentacao.id");
        CBOrder.addItem("area, nome");
        orders.add("area, apresentacao.nome");
        CBOrder.addItem("area, unidade, id");
        orders.add("area, unidade, apresentacao.id");
        CBOrder.addItem("area, unidade, nome");
        orders.add("area, unidade, apresentacao.nome");

        CBArea.removeAllItems();
        CBArea.addItem("Todas");
        areas = BancoDeDados.comando().getAreas();
        for (area area : areas) {
            CBArea.addItem(area.getNome());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        CBEvento = new javax.swing.JComboBox();
        BTGerarAnaisDoSeminario = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TFNome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBModalidade = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        CBUnidade = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        CBOrder = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        CBArea = new javax.swing.JComboBox();
        LAviso = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        SPPaginasCapa = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        TFPrefixoLink = new javax.swing.JTextField();
        CHIncluirSubarea = new javax.swing.JCheckBox();
        BTGerarCertificados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Evento");

        CBEvento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BTGerarAnaisDoSeminario.setForeground(new java.awt.Color(0, 51, 51));
        BTGerarAnaisDoSeminario.setText("Gerar Anais do seminário");
        BTGerarAnaisDoSeminario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGerarAnaisDoSeminarioActionPerformed(evt);
            }
        });

        jLabel4.setText("Nome do arquivo a ser gerado");

        TFNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFNome.setText("AnaisSEPIN");
        TFNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFNomeActionPerformed(evt);
            }
        });

        jLabel5.setText("Modalidade");

        CBModalidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setText("Unidade");

        CBUnidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel7.setText("Ordenar por:");

        CBOrder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CBOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBOrderActionPerformed(evt);
            }
        });

        jLabel8.setText("Grande Area");

        CBArea.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LAviso.setForeground(new java.awt.Color(204, 0, 0));
        LAviso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LAviso.setText(".");

        jLabel9.setText("Número de páginas de capa:");

        SPPaginasCapa.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(-1), null, Integer.valueOf(1)));
        SPPaginasCapa.setValue(3);

        jLabel10.setText("Prefixo do link dos arquivos");

        TFPrefixoLink.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TFPrefixoLink.setText("https://www.google.com.br/#q=");
        TFPrefixoLink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFPrefixoLinkActionPerformed(evt);
            }
        });

        CHIncluirSubarea.setText("Incluir Area nos anais");

        BTGerarCertificados.setForeground(new java.awt.Color(0, 51, 51));
        BTGerarCertificados.setText("Gerar de Area em Area");
        BTGerarCertificados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTGerarCertificadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CBModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBEvento, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(CBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CBArea, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAviso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TFPrefixoLink)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SPPaginasCapa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TFNome)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(CHIncluirSubarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(BTGerarAnaisDoSeminario, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(125, 125, 125)
                    .addComponent(BTGerarCertificados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CBEvento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CBModalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(CBUnidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CBArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CBOrder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(SPPaginasCapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TFNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CHIncluirSubarea))
                .addGap(14, 14, 14)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TFPrefixoLink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BTGerarAnaisDoSeminario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(LAviso)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(341, Short.MAX_VALUE)
                    .addComponent(BTGerarCertificados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(26, 26, 26)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTGerarAnaisDoSeminarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGerarAnaisDoSeminarioActionPerformed
        int mod, unidade, area;
        if (CBModalidade.getSelectedIndex() == 0) {
            mod = -1;
        } else {
            mod = modalidades.get(CBModalidade.getSelectedIndex() - 1).getId();
        }

        if (CBUnidade.getSelectedIndex() == 0) {
            unidade = -1;
        } else {
            unidade = unidades.get(CBUnidade.getSelectedIndex() - 1).getId();
        }
        if (CBArea.getSelectedIndex() == 0) {
            area = -1;
        } else {
            area = areas.get(CBArea.getSelectedIndex() - 1).getId();
        }

        apresentacoes = BancoDeDados.comando().recApresentacoesParaGerarAnaisDoSeminario(eventos.get(CBEvento.getSelectedIndex()).getId(), mod, unidade,
                orders.get(CBOrder.getSelectedIndex()), area);

        int initialC = apresentacoes.size();
        System.out.println("Iniciado retirada de trabalhos que não estão ok dos anais...");
        ArrayList<apresentacao> aps2 = new ArrayList<>();
        for (int a = 0; a < apresentacoes.size(); a++) {
            if (BancoDeDados.comando().trabalhoOkParaAnaisCertificado(apresentacoes.get(a), eventos.get(CBEvento.getSelectedIndex()))) {
                aps2.add(apresentacoes.get(a));
            }
        }
        apresentacoes = aps2;
        System.out.println(aps2.size()+"/"+initialC+" Apresentações podem entrar nos anais devido a avaliações suficientes.");

        GeradorPDF.comando().setPrefixoLink(TFPrefixoLink.getText());
        GeradorPDF.comando().setIncluirSubarea(CHIncluirSubarea.isSelected());

        //if(GeradorPDF.comando().gerarODT(apresentacoes,TFNome.getText(),(int)SPPaginasCapa.getValue()))
        if (GeradorPDF.comando().gerarArquivos(apresentacoes, TFNome.getText(), (int) SPPaginasCapa.getValue(), eventos.get(CBEvento.getSelectedIndex()))) {
            LAviso.setText("Arquivo salvo com sucesso!");
        } else {
            LAviso.setText("Falha ao salvar o arquivo!");
        }


    }//GEN-LAST:event_BTGerarAnaisDoSeminarioActionPerformed

    private void CBOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CBOrderActionPerformed

    private void TFNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFNomeActionPerformed

    private void TFPrefixoLinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFPrefixoLinkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFPrefixoLinkActionPerformed

    private void BTGerarCertificadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTGerarCertificadosActionPerformed
        ArrayList<apresentacao> apresentacoes;

        GeradorPDF.comando().setPrefixoLink(TFPrefixoLink.getText());
        GeradorPDF.comando().setIncluirSubarea(CHIncluirSubarea.isSelected());

        for (area a : areas) {
            apresentacoes = BancoDeDados.comando().recApresentacoesParaGerarAnaisDoSeminario(eventos.get(CBEvento.getSelectedIndex()).getId(), -1, -1,
                    orders.get(CBOrder.getSelectedIndex()), a.getId());

            //if(GeradorPDF.comando().gerarODT(apresentacoes,TFNome.getText(),(int)SPPaginasCapa.getValue()))
            if (GeradorPDF.comando().gerarArquivos(apresentacoes, TFNome.getText() + "_" + a.getNome(), (int) SPPaginasCapa.getValue(), eventos.get(CBEvento.getSelectedIndex()))) {
                LAviso.setText("Arquivo salvo com sucesso!");
            } else {
                LAviso.setText("Falha ao salvar o arquivo!");
            }
        }

    }//GEN-LAST:event_BTGerarCertificadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarAnaisDoSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarAnaisDoSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarAnaisDoSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarAnaisDoSeminario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GerarAnaisDoSeminario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTGerarAnaisDoSeminario;
    private javax.swing.JButton BTGerarCertificados;
    private javax.swing.JComboBox CBArea;
    private javax.swing.JComboBox CBEvento;
    private javax.swing.JComboBox CBModalidade;
    private javax.swing.JComboBox CBOrder;
    private javax.swing.JComboBox CBUnidade;
    private javax.swing.JCheckBox CHIncluirSubarea;
    private javax.swing.JLabel LAviso;
    private javax.swing.JSpinner SPPaginasCapa;
    private javax.swing.JTextField TFNome;
    private javax.swing.JTextField TFPrefixoLink;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
